spring:
  application:
    name: cyber-game-management
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
